import canonicalLaneMathlib.AdmissibleClass
import MaterialsComputationalMaterialsDiscoveryFoundationCanonicalLaneLean.CrystalStructureAdmissible
import MaterialsComputationalMaterialsDiscoveryFoundationCanonicalLaneLean.DensityFunctionalTheory

namespace HautevilleHouse
namespace MaterialsComputationalMaterialsDiscoveryFoundationCanonicalLaneLean

def ConstrainedMaterialsClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_materials_endgame (A : AdmissibleClass) : ConstrainedMaterialsClosure A :=
  And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end MaterialsComputationalMaterialsDiscoveryFoundationCanonicalLaneLean
end HautevilleHouse